apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    abc: xyz
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000
    protocol: TCP
  selector:
    env: prod
