apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
 # namespace: awesomeapps
spec:
  containers:
    - name: sample-pod
      image: nginx
      ports :
      - containerPort: 80
  imagePullSecrets:
    - name: registry-secret
    
